### ISSUE TITLE
Panic if you toggle the ms/frame stat

### ISSUE THREAD

**Issue by paul-hansen** [laundmo/bevy_screen_diagnostics#3]
## What I want to do
I would like to be able to toggle the `fps` and the `ms/frame` stats separately.

## What I tried
Changing this line in the `runtime_configure` example:
https://github.com/laundmo/bevy_screen_diagnostics/blob/0e2d3b5205c54e90c5ea57dfe387ef14ffaac030/examples/runtime_configure.rs#L40
To this:
```rust
diags.modify("ms/frame").toggle();
```

## What I expected
I expected it to toggle the ms/frame stat display instead of the fps display.

## What happened 

Causes a panic when clicking the left mouse button, with the message: `index out of bounds: the len is 2 but the index is 2`
Stack trace points to this line:
https://github.com/laundmo/bevy_screen_diagnostics/blob/0e2d3b5205c54e90c5ea57dfe387ef14ffaac030/src/lib.rs#L345

<details>
  <summary>Click for stack trace</summary>
  
  ```
  thread 'Compute Task Pool (13)' panicked at 'index out of bounds: the len is 2 but the index is 2', C:\Users\Paul\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_screen_diagnostics-0.2.0\src\lib.rs:345:17
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\panicking.rs:64
   2: core::panicking::panic_bounds_check
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\panicking.rs:147
   3: core::slice::index::impl$2::index_mut
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\core\src\slice\index.rs:266
   4: core::slice::index::impl$1::index_mut
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\core\src\slice\index.rs:30
   5: alloc::vec::impl$16::index_mut
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\alloc\src\vec\mod.rs:2739
   6: bevy_screen_diagnostics::ScreenDiagnostics::update
             at C:\Users\Paul\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_screen_diagnostics-0.2.0\src\lib.rs:345
   7: bevy_screen_diagnostics::update_diags
             at C:\Users\Paul\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_screen_diagnostics-0.2.0\src\lib.rs:442
   8: core::ops::function::FnMut::call_mut
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\core\src\ops\function.rs:337
   9: core::ops::function::impls::impl$3::call_mut<tuple$<bevy_ecs::change_detection::ResMut<bevy_screen_diagnostics::ScreenDiagnostics>,bevy_ecs::change_detection::Res<bevy_diagnostic::diagnostic::Diagnostics>,bevy_ecs::system::query::Query<ref_mut$<bevy_text:
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\core\src\ops\function.rs:618
  10: bevy_ecs::system::function_system::impl$15::run::call_inner
             at C:\Users\Paul\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.10.0\src\system\function_system.rs:629
  11: bevy_ecs::system::function_system::impl$15::run
             at C:\Users\Paul\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.10.0\src\system\function_system.rs:632
  12: bevy_ecs::system::function_system::impl$6::run_unsafe<void (*)(bevy_ecs::change_detection::ResMut<bevy_screen_diagnostics::ScreenDiagnostics>,bevy_ecs::change_detection::Res<bevy_diagnostic::diagnostic::Diagnostics>,bevy_ecs::system::query::Query<ref_mut$
             at C:\Users\Paul\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.10.0\src\system\function_system.rs:466
  13: bevy_ecs::schedule::executor::multi_threaded::impl$3::spawn_system_task::async_block$0::closure$0
             at C:\Users\Paul\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.10.0\src\schedule\executor\multi_threaded.rs:448
  14: core::ops::function::FnOnce::call_once
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\core\src\ops\function.rs:507
  15: core::panic::unwind_safe::impl$23::call_once
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\core\src\panic\unwind_safe.rs:271
  16: std::panicking::try::do_call
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\std\src\panicking.rs:483
  17: std::panicking::try
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\std\src\panicking.rs:447
  18: std::panic::catch_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\std\src\panic.rs:137
  19: bevy_ecs::schedule::executor::multi_threaded::impl$3::spawn_system_task::async_block$0
             at C:\Users\Paul\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.10.0\src\schedule\executor\multi_threaded.rs:446
  20: async_executor::impl$4::spawn::async_block$0
             at C:\Users\Paul\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.5.0\src\lib.rs:139
  21: async_task::raw::RawTask<enum2$<async_executor::impl$4::spawn::async_block_env$0<tuple$<>,enum2$<bevy_ecs::schedule::executor::multi_threaded::impl$3::spawn_system_task::async_block_env$0> > >,tuple$<>,async_executor::impl$4::schedule::closure_env$0>::run
             at C:\Users\Paul\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.3.0\src\raw.rs:511
  22: async_executor::impl$4::run::async_fn$0::async_block$0
             at C:\Users\Paul\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.5.0\src\lib.rs:230
  23: futures_lite::future::impl$12::poll<enum2$<core::result::Result<tuple$<>,async_channel::RecvError> >,futures_lite::future::Or<enum2$<bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0::closure$0::closure$0::async_block_env$0>,async_channel:
             at C:\Users\Paul\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-lite-1.12.0\src\future.rs:529
  24: async_executor::impl$4::run::async_fn$0<enum2$<core::result::Result<tuple$<>,async_channel::RecvError> >,futures_lite::future::Or<enum2$<bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0::closure$0::closure$0::async_block_env$0>,async_chan
             at C:\Users\Paul\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.5.0\src\lib.rs:237
  25: futures_lite::future::block_on::closure$0
             at C:\Users\Paul\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-lite-1.12.0\src\future.rs:89
  26: std::thread::local::LocalKey<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> > >::try_with
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\std\src\thread\local.rs:446
  27: std::thread::local::LocalKey<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> > >::with<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> >,futures_lite::future::block_on::closure_env$0<enum2$<core::result::Result<tupl
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\std\src\thread\local.rs:422
  28: bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0::closure$0::closure$0
             at C:\Users\Paul\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_tasks-0.10.0\src\task_pool.rs:171
  29: std::panicking::try::do_call
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\std\src\panicking.rs:483
  30: std::panicking::try<enum2$<core::result::Result<tuple$<>,async_channel::RecvError> >,bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0::closure$0::closure_env$0>
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\std\src\panicking.rs:447
  31: std::panic::catch_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\std\src\panic.rs:137
  32: bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0::closure$0
             at C:\Users\Paul\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_tasks-0.10.0\src\task_pool.rs:165
  33: std::thread::local::LocalKey<async_executor::LocalExecutor>::try_with
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\std\src\thread\local.rs:446
  34: std::thread::local::LocalKey<async_executor::LocalExecutor>::with<async_executor::LocalExecutor,bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0::closure_env$0,tuple$<> >  
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\std\src\thread\local.rs:422
  35: bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0
             at C:\Users\Paul\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_tasks-0.10.0\src\task_pool.rs:158
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  ```
</details>

Is this a bug or am I using it wrong?

Thanks for making this library! Super useful to have something to drop in quick for this.

**Comment by laundmo** [comment]
well, i can tell you for sure that that's supposed to be the correct usage. investigating.

**Comment by laundmo** [comment]
Alright got a solution ready, publishing.

**Comment by laundmo** [comment]
Done! Using `cargo update` should get you the fixed version.

**Comment by paul-hansen** [comment]
It works, thanks!
